import { Product } from "@/types/categories";

export const nm355WavelengthConversionLaser: Product = {
  slug: "355nm-wavelength-conversion-laser",
  category: "wavelength-conversion-lasers",

  meta: {
    title: "Techwin 355 nm Wavelength Conversion Laser | UV Laser Systems",
    description:
      "Techwin 355 nm Wavelength Conversion Laser for UV optics, sensing and research needs in Hangzhou City. Reliable laser performance. Contact +86-13958180450 for details.",
    keywords:
      "355 nm laser, UV wavelength conversion, THG laser, ultraviolet laser source, Techwin 355nm, UV optics laser"
  },

  title: "355 nm Wavelength Conversion Laser",

  shortDescription:
    "Ultraviolet (UV) wavelength conversion laser at 355 nm for precision measurement, semiconductor processes, scientific research and material interaction applications.",

  heroImage: {
    src: "/products/Wavelength-Conversion-Lasers/355nm-hero.jpg",
    alt: "355 nm Wavelength Conversion Laser"
  },

  galleryImages: [
    { src: "/products/Wavelength-Conversion-Lasers/355nm-lab.jpg", alt: "355 nm laser in lab" },
    { src: "/products/Wavelength-Conversion-Lasers/355nm-module.jpg", alt: "355 nm conversion module" },
    { src: "/products/Wavelength-Conversion-Lasers/355nm-diagram.jpg", alt: "355 nm UV conversion diagram" }
  ],

  datasheetUrl: "/datasheets/tn-355nm-wavelength-conversion-laser.pdf",

  sections: [
    {
      type: "text",
      heading: "Introduction to 355 nm UV Wavelength Conversion",
      image: { src: "/products/Wavelength-Conversion-Lasers/355nm-intro.jpg", alt: "355 nm UV introduction" },
      content:
        "The 355 nm UV laser is achieved through nonlinear optical conversion using third-harmonic generation (THG). This wavelength is widely used in semiconductor processing, optical research, fluorescence excitation and UV-based sensing systems due to its high spatial resolution and strong interaction with sensitive materials."
    },

    {
      type: "features",
      heading: "Key Features of 355 nm Wavelength Conversion Lasers",
      bullets: [
        "High beam quality for precise UV interaction",
        "Excellent long-term output stability",
        "Low-noise ultraviolet emission for sensitive detection",
        "Compact and rugged design suitable for OEM platforms",
        "Advanced thermal and mechanical stability",
        "High-efficiency nonlinear conversion structure"
      ]
    },

    {
      type: "text",
      heading: "How a 355 nm Wavelength Conversion Laser Works",
      content:
        "The 355 nm UV output is generated by converting a stable IR fundamental wavelength (e.g., 1064 nm) using nonlinear crystals configured for third-harmonic generation. Internal stabilization, precision filtering and thermal management ensure clean UV output with minimal drift during continuous operation."
    },

    {
      type: "features",
      heading: "Applications of 355 nm Wavelength Conversion Lasers",
      bullets: [
        "Precision material processing and micromachining",
        "Semiconductor inspection, lithography support and wafer alignment",
        "UV-fluorescence excitation and photonics research",
        "Environmental sensing and absorption-based detection",
        "High-accuracy industrial UV instrumentation"
      ]
    },

    {
      type: "text",
      heading: "Why the 355 nm UV Range Is Important",
      content:
        "The 355 nm UV band offers strong material absorption, low thermal impact, superior focusing ability and excellent fluorescence excitation efficiency. These characteristics make it ideal for semiconductor, scientific, and high-resolution optical tasks."
    },

    {
      type: "features",
      heading: "Technical Considerations",
      bullets: [
        "Wavelength stability for measurement accuracy",
        "Beam quality optimized for fine focusing",
        "Long-term UV output consistency",
        "Power options tailored to application needs",
        "Cooling systems designed for thermal reliability",
        "Crystal longevity for predictable operation"
      ]
    },

    {
      type: "text",
      heading: "Common Industries Using 355 nm UV Lasers",
      content:
        "This wavelength is heavily used in research labs, semiconductor manufacturing, environmental monitoring, micro-machining facilities, UV-based optical instruments and sensitive biological detection applications."
    },

    {
      type: "text",
      heading: "Why Choose This UV Laser Category?",
      content:
        "A 355 nm wavelength conversion system provides proven UV performance with narrow linewidth, stable long-term operation and strong system integration compatibility. Designed with high-quality optical components and precise engineering, it supports demanding scientific and industrial environments."
    }
  ],

  relatedProducts: [
    {
      slug: "266nm-wavelength-conversion-laser",
      title: "266 nm Wavelength Conversion Laser",
      shortDescription: "Deep UV fourth-harmonic system for high-energy absorption applications.",
      image: { src: "/products/Wavelength-Conversion-Lasers/266nm-thumb.jpg", alt: "266 nm conversion laser" },
      href: "/products/wavelength-conversion-lasers/266nm-wavelength-conversion-laser"
    },
    {
      slug: "532nm-wavelength-conversion-laser",
      title: "532 nm Wavelength Conversion Laser",
      shortDescription: "Visible green SHG laser for metrology and photonics use.",
      image: { src: "/products/Wavelength-Conversion-Lasers/532nm-thumb.jpg", alt: "532 nm conversion laser" },
      href: "/products/wavelength-conversion-lasers/532nm-wavelength-conversion-laser"
    }
  ]
};

export default nm355WavelengthConversionLaser;
